"""исправоение

Revision ID: 28084815c02c
Revises: bf30a717ae85
Create Date: 2024-10-12 12:57:03.671610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28084815c02c'
down_revision: Union[str, None] = 'bf30a717ae85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FDUs', sa.Column('gas_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_FDUs_gas_id'), 'FDUs', ['gas_id'], unique=False)
    op.create_foreign_key(None, 'FDUs', 'Gases', ['gas_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FDUs', type_='foreignkey')
    op.drop_index(op.f('ix_FDUs_gas_id'), table_name='FDUs')
    op.drop_column('FDUs', 'gas_id')
    # ### end Alembic commands ###
