"""user review relationship

Revision ID: 3aaf66edd63a
Revises: 20b7ebadca7e
Create Date: 2024-10-16 14:23:57.004858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaf66edd63a'
down_revision: Union[str, None] = '20b7ebadca7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Users_review_id', table_name='Users')
    op.drop_constraint('Users_review_id_fkey', 'Users', type_='foreignkey')
    op.drop_column('Users', 'review_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Users_review_id_fkey', 'Users', 'Reviews', ['review_id'], ['id'])
    op.create_index('ix_Users_review_id', 'Users', ['review_id'], unique=False)
    # ### end Alembic commands ###
