"""cr

Revision ID: 8c51479061eb
Revises: 6ba57fb3deac
Create Date: 2024-10-12 23:41:22.056969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c51479061eb'
down_revision: Union[str, None] = '6ba57fb3deac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_fdu',
    sa.Column('fuel_id', sa.Integer(), nullable=False),
    sa.Column('fdu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fdu_id'], ['FDUs.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['Fuels.id'], ),
    sa.PrimaryKeyConstraint('fuel_id', 'fdu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_fdu')
    # ### end Alembic commands ###
