"""initial migration for test-gas1

Revision ID: b8d3df9124b4
Revises: 
Create Date: 2024-10-30 13:44:56.126967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d3df9124b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Gases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adress', sa.String(), nullable=True),
    sa.Column('photo', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Gases_id'), 'Gases', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('regdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('loyaltylvl', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('FDUs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gas_id', sa.Integer(), nullable=True),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gas_id'], ['Gases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FDUs_gas_id'), 'FDUs', ['gas_id'], unique=False)
    op.create_index(op.f('ix_FDUs_id'), 'FDUs', ['id'], unique=False)
    op.create_table('Reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gas_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gas_id'], ['Gases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Reviews_gas_id'), 'Reviews', ['gas_id'], unique=False)
    op.create_index(op.f('ix_Reviews_id'), 'Reviews', ['id'], unique=False)
    op.create_index(op.f('ix_Reviews_user_id'), 'Reviews', ['user_id'], unique=False)
    op.create_table('Fuels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('fdus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fdus_id'], ['FDUs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Fuels_id'), 'Fuels', ['id'], unique=False)
    op.create_table('fuel_fdu',
    sa.Column('fuel_id', sa.Integer(), nullable=False),
    sa.Column('fdu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fdu_id'], ['FDUs.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['Fuels.id'], ),
    sa.PrimaryKeyConstraint('fuel_id', 'fdu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_fdu')
    op.drop_index(op.f('ix_Fuels_id'), table_name='Fuels')
    op.drop_table('Fuels')
    op.drop_index(op.f('ix_Reviews_user_id'), table_name='Reviews')
    op.drop_index(op.f('ix_Reviews_id'), table_name='Reviews')
    op.drop_index(op.f('ix_Reviews_gas_id'), table_name='Reviews')
    op.drop_table('Reviews')
    op.drop_index(op.f('ix_FDUs_id'), table_name='FDUs')
    op.drop_index(op.f('ix_FDUs_gas_id'), table_name='FDUs')
    op.drop_table('FDUs')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Gases_id'), table_name='Gases')
    op.drop_table('Gases')
    # ### end Alembic commands ###
